const SPOTS = [
  // ===== Paris (12) =====
  { id: "paris-louvre", name: "ルーヴル美術館", region: "paris",
    categories: ["culture","history"], timeSlot: "morning", hours: 3,
    lat: 48.8606, lng: 2.3376,
    description: "世界最大級の美術館。モナ・リザやミロのヴィーナスなど必見の傑作が揃う。",
    tip: "水曜・金曜は夜間開館。事前チケット購入推奨。" },
  { id: "paris-eiffel", name: "エッフェル塔", region: "paris",
    categories: ["culture","history"], timeSlot: "afternoon", hours: 2,
    lat: 48.8584, lng: 2.2945,
    description: "パリのシンボル。展望台からの眺めは圧巻。",
    tip: "夜のライトアップも美しい。エレベーターは混雑するので階段もおすすめ。" },
  { id: "paris-montmartre", name: "モンマルトル地区", region: "paris",
    categories: ["culture","shopping"], timeSlot: "morning", hours: 3,
    lat: 48.8867, lng: 2.3431,
    description: "サクレ・クール寺院を中心とした芸術家の街。テルトル広場で似顔絵描きも。",
    tip: "スリに注意。朝早めの訪問が快適。" },
  { id: "paris-orsay", name: "オルセー美術館", region: "paris",
    categories: ["culture","history"], timeSlot: "afternoon", hours: 2.5,
    lat: 48.8600, lng: 2.3266,
    description: "印象派の名作が集結。モネ、ルノワール、ゴッホなどの作品を堪能。",
    tip: "木曜は夜間開館。ルーヴルとセットで訪れると効率的。" },
  { id: "paris-marais", name: "マレ地区散策", region: "paris",
    categories: ["shopping","food"], timeSlot: "afternoon", hours: 2.5,
    lat: 48.8566, lng: 2.3622,
    description: "おしゃれなブティックやカフェが並ぶトレンドエリア。歴史的建造物も点在。",
    tip: "日曜でも多くの店が営業している珍しいエリア。" },
  { id: "paris-seine", name: "セーヌ川クルーズ", region: "paris",
    categories: ["nature","culture"], timeSlot: "evening", hours: 1.5,
    lat: 48.8611, lng: 2.3069,
    description: "船上からパリの名所を一望。夕暮れ時の景色が特に美しい。",
    tip: "バトームーシュは予約なしでも乗船可能。ディナークルーズもあり。" },
  { id: "paris-notredame", name: "ノートルダム大聖堂周辺", region: "paris",
    categories: ["history","culture"], timeSlot: "morning", hours: 1.5,
    lat: 48.8530, lng: 2.3499,
    description: "ゴシック建築の傑作。修復中だが外観と周辺のシテ島散策は楽しめる。",
    tip: "シテ島の花市場も立ち寄りスポット。" },
  { id: "paris-champselysees", name: "シャンゼリゼ通り", region: "paris",
    categories: ["shopping","food"], timeSlot: "evening", hours: 2,
    lat: 48.8698, lng: 2.3076,
    description: "世界で最も美しい通りと称される大通り。ブランドショップやカフェが並ぶ。",
    tip: "凱旋門の展望台からの眺めもおすすめ。夜のイルミネーションが華やか。" },
  { id: "paris-versailles", name: "ヴェルサイユ宮殿", region: "paris",
    categories: ["history","culture","nature"], timeSlot: "morning", hours: 4,
    lat: 48.8049, lng: 2.1204,
    description: "太陽王ルイ14世が建てた豪華絢爛な宮殿。広大な庭園も必見。",
    tip: "パリから電車で約40分。丸一日かけてじっくり見学を。火曜休館。" },
  { id: "paris-latinquarter", name: "カルチエ・ラタン", region: "paris",
    categories: ["food","culture"], timeSlot: "evening", hours: 2,
    lat: 48.8494, lng: 2.3445,
    description: "学生街として知られる活気あるエリア。手頃なレストランが多数。",
    tip: "リュクサンブール公園での散歩と組み合わせると良い。" },
  { id: "paris-gourmet", name: "パリのグルメツアー", region: "paris",
    categories: ["food"], timeSlot: "morning", hours: 3,
    lat: 48.8530, lng: 2.3270,
    description: "パン屋、チーズ店、マルシェを巡るグルメ体験。本場の味を堪能。",
    tip: "マルシェは午前中がベスト。ラスパイユのビオマルシェは日曜開催。" },
  { id: "paris-moulinrouge", name: "ムーラン・ルージュ", region: "paris",
    categories: ["culture"], timeSlot: "evening", hours: 2.5,
    lat: 48.8841, lng: 2.3322,
    description: "世界的に有名なキャバレー。華やかなショーを楽しめる。",
    tip: "事前予約必須。ディナー付きプランもあり。" },

  // ===== Lyon (8) =====
  { id: "lyon-vieuxlyon", name: "旧市街（ヴュー・リヨン）", region: "lyon",
    categories: ["history","culture"], timeSlot: "morning", hours: 2.5,
    lat: 45.7620, lng: 4.8270,
    description: "ルネサンス建築が残る世界遺産の旧市街。トラブールと呼ばれる秘密の通路も。",
    tip: "ガイドツアーに参加するとトラブールの歴史がよくわかる。" },
  { id: "lyon-gastronomy", name: "リヨン美食めぐり", region: "lyon",
    categories: ["food"], timeSlot: "morning", hours: 3,
    lat: 45.7640, lng: 4.8357,
    description: "フランス美食の都。ブション（伝統的ビストロ）で本場のリヨン料理を。",
    tip: "クネル、サラダ・リヨネーズなど郷土料理を試して。ランチが狙い目。" },
  { id: "lyon-fourviere", name: "フルヴィエール大聖堂", region: "lyon",
    categories: ["history","culture"], timeSlot: "afternoon", hours: 2,
    lat: 45.7622, lng: 4.8222,
    description: "丘の上に立つ白亜の大聖堂。リヨンの街を一望できるパノラマビュー。",
    tip: "ケーブルカーで楽にアクセス可能。隣接のローマ劇場跡も見学を。" },
  { id: "lyon-hallpaulbocuse", name: "ポール・ボキューズ市場", region: "lyon",
    categories: ["food","shopping"], timeSlot: "morning", hours: 2,
    lat: 45.7630, lng: 4.8500,
    description: "リヨンの台所と呼ばれる屋内市場。チーズ、シャルキュトリ、ワインなど。",
    tip: "土曜の午前が最も活気がある。試食を楽しみながら散策。" },
  { id: "lyon-confluence", name: "コンフリュアンス地区", region: "lyon",
    categories: ["culture","shopping"], timeSlot: "afternoon", hours: 2,
    lat: 45.7380, lng: 4.8180,
    description: "再開発された近代的エリア。コンフリュアンス博物館やショッピングモール。",
    tip: "建築好きなら必見のエリア。川沿いの散歩も気持ちいい。" },
  { id: "lyon-parcdelatete", name: "テット・ドール公園", region: "lyon",
    categories: ["nature"], timeSlot: "afternoon", hours: 2,
    lat: 45.7770, lng: 4.8555,
    description: "リヨン最大の都市公園。湖、動物園（無料）、バラ園がある。",
    tip: "レンタルボートで湖を楽しめる。ピクニックにも最適。" },
  { id: "lyon-presquile", name: "プレスキル地区", region: "lyon",
    categories: ["shopping","culture"], timeSlot: "evening", hours: 2,
    lat: 45.7580, lng: 4.8350,
    description: "二つの川に挟まれた半島状の中心地。ベルクール広場を中心に賑わう。",
    tip: "テロー広場の噴水は夜ライトアップされて美しい。" },
  { id: "lyon-murales", name: "だまし絵壁画めぐり", region: "lyon",
    categories: ["culture"], timeSlot: "morning", hours: 2,
    lat: 45.7690, lng: 4.8290,
    description: "リヨン名物の巨大トロンプ・ルイユ壁画。カニュの壁など見応え十分。",
    tip: "自転車で回ると効率的。市内に約100以上の壁画がある。" },

  // ===== Marseille (8) =====
  { id: "marseille-vieuxport", name: "旧港（ヴュー・ポール）", region: "marseille",
    categories: ["culture","food"], timeSlot: "morning", hours: 2,
    lat: 43.2951, lng: 5.3742,
    description: "マルセイユの中心地。朝の魚市場やカフェで地中海の雰囲気を満喫。",
    tip: "日曜の朝に魚市場が開かれる。ブイヤベースの名店も周辺に。" },
  { id: "marseille-notredame", name: "ノートルダム・ド・ラ・ガルド大聖堂", region: "marseille",
    categories: ["history","culture"], timeSlot: "morning", hours: 1.5,
    lat: 43.2840, lng: 5.3713,
    description: "マルセイユを見守る丘の上の大聖堂。市内と地中海を一望できる絶景。",
    tip: "徒歩でも行けるが、プチトランやバスが楽。" },
  { id: "marseille-calanques", name: "カランク国立公園", region: "marseille",
    categories: ["nature"], timeSlot: "morning", hours: 4,
    lat: 43.2120, lng: 5.4500,
    description: "石灰岩の断崖とエメラルドグリーンの入り江が続く絶景の国立公園。",
    tip: "ハイキングシューズ必須。夏は入場制限あり。水と日焼け止めを忘れずに。" },
  { id: "marseille-mucem", name: "MuCEM（ヨーロッパ・地中海文明博物館）", region: "marseille",
    categories: ["culture","history"], timeSlot: "afternoon", hours: 2.5,
    lat: 43.2966, lng: 5.3609,
    description: "地中海文明をテーマにした現代的な博物館。建築自体も見どころ。",
    tip: "屋上テラスからの眺めは無料。隣のサン・ジャン要塞も合わせて見学。" },
  { id: "marseille-panier", name: "ル・パニエ地区", region: "marseille",
    categories: ["culture","shopping"], timeSlot: "afternoon", hours: 2,
    lat: 43.2990, lng: 5.3680,
    description: "マルセイユ最古の地区。カラフルな路地とストリートアートが魅力。",
    tip: "アーティストの工房やセレクトショップを探索。" },
  { id: "marseille-bouillabaisse", name: "ブイヤベース体験", region: "marseille",
    categories: ["food"], timeSlot: "evening", hours: 2,
    lat: 43.2920, lng: 5.3750,
    description: "マルセイユ名物の魚介スープ。本場の味は格別。",
    tip: "正統派の店は要予約。一人前€40〜が相場。旧港周辺に名店多数。" },
  { id: "marseille-frioul", name: "フリウル諸島", region: "marseille",
    categories: ["nature","history"], timeSlot: "afternoon", hours: 3,
    lat: 43.2800, lng: 5.3100,
    description: "旧港からフェリーで20分。イフ城（モンテ・クリスト伯の舞台）がある。",
    tip: "フェリーは頻繁に運航。半日で島を一周できる。" },
  { id: "marseille-corniche", name: "コルニッシュ海岸道路", region: "marseille",
    categories: ["nature"], timeSlot: "evening", hours: 1.5,
    lat: 43.2750, lng: 5.3600,
    description: "地中海沿いの美しい海岸道路。夕日スポットとしても人気。",
    tip: "自転車やジョギングにも最適。途中にビーチもあり。" },

  // ===== Nice (8) =====
  { id: "nice-promenade", name: "プロムナード・デ・ザングレ", region: "nice",
    categories: ["nature","culture"], timeSlot: "morning", hours: 1.5,
    lat: 43.6945, lng: 7.2530,
    description: "コートダジュールを代表する海岸沿いの遊歩道。青い海と空が広がる。",
    tip: "朝のジョギングや散歩に最適。無料のビーチも点在。" },
  { id: "nice-oldtown", name: "ニース旧市街", region: "nice",
    categories: ["food","shopping","culture"], timeSlot: "morning", hours: 2.5,
    lat: 43.6970, lng: 7.2760,
    description: "パステルカラーの建物が並ぶ迷路のような旧市街。サレヤ広場のマルシェも。",
    tip: "マルシェは毎朝開催（月曜は骨董市）。ソッカを食べてみて。" },
  { id: "nice-collineduchateau", name: "城跡公園（コリーヌ・デュ・シャトー）", region: "nice",
    categories: ["nature","history"], timeSlot: "afternoon", hours: 1.5,
    lat: 43.6952, lng: 7.2818,
    description: "ニースの街と海を一望できる丘の上の公園。滝や遺跡もある。",
    tip: "エレベーターで楽に登れる。夕暮れ時がベストタイム。" },
  { id: "nice-matisse", name: "マティス美術館", region: "nice",
    categories: ["culture"], timeSlot: "afternoon", hours: 2,
    lat: 43.7197, lng: 7.2753,
    description: "アンリ・マティスの作品を集めた美術館。南仏の光と色彩を感じる。",
    tip: "シャガール美術館とセットで訪問がおすすめ。" },
  { id: "nice-chagall", name: "シャガール美術館", region: "nice",
    categories: ["culture"], timeSlot: "morning", hours: 1.5,
    lat: 43.7108, lng: 7.2700,
    description: "マルク・シャガールの聖書をテーマにした作品群。色彩豊かな大作に圧倒。",
    tip: "オーディオガイド（日本語あり）で理解が深まる。" },
  { id: "nice-cuisine", name: "ニース料理体験", region: "nice",
    categories: ["food"], timeSlot: "evening", hours: 2,
    lat: 43.6960, lng: 7.2720,
    description: "サラダ・ニソワーズ、ラタトゥイユなど地中海の恵みを味わう。",
    tip: "旧市街のレストランがおすすめ。テラス席で海風を感じながら。" },
  { id: "nice-eze", name: "エズ村日帰り", region: "nice",
    categories: ["nature","history","shopping"], timeSlot: "morning", hours: 3,
    lat: 43.7281, lng: 7.3612,
    description: "鷲の巣村と呼ばれる断崖の上の中世の村。地中海を見下ろす絶景。",
    tip: "バスで約30分。フラゴナールの香水工場見学も人気。" },
  { id: "nice-nightlife", name: "ニースの夜散歩", region: "nice",
    categories: ["food","culture"], timeSlot: "evening", hours: 2,
    lat: 43.6977, lng: 7.2700,
    description: "ライトアップされた海岸通りやマセナ広場を散策。バーやジェラテリアも。",
    tip: "マセナ広場の光るオブジェは夜がおすすめ。" },

  // ===== Bordeaux (8) =====
  { id: "bordeaux-citeduvent", name: "ラ・シテ・デュ・ヴァン（ワイン博物館）", region: "bordeaux",
    categories: ["culture","food"], timeSlot: "morning", hours: 3,
    lat: 44.8625, lng: -0.5509,
    description: "ワインの歴史と文化を体験できる近代的な博物館。最上階で試飲も。",
    tip: "所要時間は2〜3時間。展望デッキからのガロンヌ川の眺めも素晴らしい。" },
  { id: "bordeaux-saintmilion", name: "サン・テミリオン", region: "bordeaux",
    categories: ["food","history","nature"], timeSlot: "morning", hours: 4,
    lat: 44.8944, lng: -0.1545,
    description: "世界遺産のワイン産地。中世の街並みとブドウ畑が広がる美しい村。",
    tip: "ボルドーから電車で約35分。シャトー見学はツアー参加が便利。" },
  { id: "bordeaux-placedelabourse", name: "ブルス広場と水鏡", region: "bordeaux",
    categories: ["culture"], timeSlot: "evening", hours: 1,
    lat: 44.8414, lng: -0.5694,
    description: "世界最大の水鏡に映る18世紀の建築群。夜のライトアップは幻想的。",
    tip: "夏は水遊びする地元の人々で賑わう。写真撮影のベストスポット。" },
  { id: "bordeaux-oldtown", name: "ボルドー旧市街散策", region: "bordeaux",
    categories: ["history","shopping"], timeSlot: "afternoon", hours: 2.5,
    lat: 44.8378, lng: -0.5717,
    description: "18世紀の美しい建築群が残るユネスコ世界遺産。グラン・テアトルも必見。",
    tip: "サント・カトリーヌ通りはヨーロッパ最長の歩行者天国。" },
  { id: "bordeaux-winebar", name: "ボルドーワインバー巡り", region: "bordeaux",
    categories: ["food"], timeSlot: "evening", hours: 2.5,
    lat: 44.8404, lng: -0.5750,
    description: "世界最高峰のワイン産地で本場のワインを味わう。グラスワインから楽しめる。",
    tip: "バー・ア・ヴァンで気軽にテイスティング。ソムリエに相談を。" },
  { id: "bordeaux-caneles", name: "カヌレ食べ比べ", region: "bordeaux",
    categories: ["food"], timeSlot: "afternoon", hours: 1.5,
    lat: 44.8370, lng: -0.5730,
    description: "ボルドー発祥の焼き菓子。パリパリの外側としっとり中身が絶品。",
    tip: "バイヤルダンやラ・トリュシュテールが人気店。" },
  { id: "bordeaux-darwin", name: "ダーウィン・エコシステム", region: "bordeaux",
    categories: ["culture","food"], timeSlot: "afternoon", hours: 2,
    lat: 44.8500, lng: -0.5550,
    description: "旧軍施設をリノベーションしたオルタナティブスペース。カフェやストリートアートも。",
    tip: "週末にマルシェやイベントが開催されることも。" },
  { id: "bordeaux-garonne", name: "ガロンヌ川クルーズ", region: "bordeaux",
    categories: ["nature","culture"], timeSlot: "evening", hours: 1.5,
    lat: 44.8450, lng: -0.5650,
    description: "川沿いからボルドーの美しい建築群を眺めるクルーズ。",
    tip: "サンセットクルーズが特に人気。ワイン付きプランもあり。" },

  // ===== Strasbourg (8) =====
  { id: "strasbourg-petite", name: "プティット・フランス", region: "strasbourg",
    categories: ["history","culture"], timeSlot: "morning", hours: 2,
    lat: 48.5800, lng: 7.7410,
    description: "木組みの家が並ぶ運河沿いの美しい地区。ストラスブール随一の撮影スポット。",
    tip: "朝の柔らかい光の中での散策がおすすめ。" },
  { id: "strasbourg-cathedral", name: "ストラスブール大聖堂", region: "strasbourg",
    categories: ["history","culture"], timeSlot: "morning", hours: 2,
    lat: 48.5818, lng: 7.7510,
    description: "ゴシック建築の傑作。天文時計は毎日12時半に動く精巧なからくり時計。",
    tip: "塔の展望台（332段）からアルザスの平原を一望。天文時計は12時前に入場を。" },
  { id: "strasbourg-european", name: "ヨーロッパ地区", region: "strasbourg",
    categories: ["culture"], timeSlot: "afternoon", hours: 1.5,
    lat: 48.5970, lng: 7.7700,
    description: "欧州議会や欧州人権裁判所がある近代的エリア。EUの中心地。",
    tip: "欧州議会は見学ツアーあり（事前予約制）。" },
  { id: "strasbourg-alsacecuisine", name: "アルザス料理体験", region: "strasbourg",
    categories: ["food"], timeSlot: "evening", hours: 2,
    lat: 48.5810, lng: 7.7490,
    description: "シュークルート、タルト・フランベ、ベッコフなどの郷土料理を楽しむ。",
    tip: "ヴィンスチューブ（ワイン居酒屋）でアルザスワインと一緒に。" },
  { id: "strasbourg-orangerie", name: "オランジュリー公園", region: "strasbourg",
    categories: ["nature"], timeSlot: "afternoon", hours: 1.5,
    lat: 48.5900, lng: 7.7720,
    description: "ストラスブール最古の公園。白鳥が泳ぐ湖やミニ動物園もある。",
    tip: "春のチューリップと秋の紅葉が美しい。ピクニックに最適。" },
  { id: "strasbourg-winstub", name: "ヴィンスチューブ巡り", region: "strasbourg",
    categories: ["food","culture"], timeSlot: "evening", hours: 2.5,
    lat: 48.5790, lng: 7.7430,
    description: "アルザス伝統のワイン酒場。地元の人々との交流も楽しい。",
    tip: "プティット・フランス周辺に雰囲気の良い店が多い。" },
  { id: "strasbourg-boat", name: "運河クルーズ", region: "strasbourg",
    categories: ["nature","culture"], timeSlot: "afternoon", hours: 1,
    lat: 48.5815, lng: 7.7450,
    description: "バトラマで巡るストラスブールの運河。水上から見る街並みは格別。",
    tip: "所要時間約70分。日本語オーディオガイドあり。" },
  { id: "strasbourg-christmas", name: "クリスマスマーケット", region: "strasbourg",
    categories: ["shopping","food","culture"], timeSlot: "evening", hours: 2.5,
    lat: 48.5820, lng: 7.7500,
    description: "フランス最古のクリスマスマーケット。11月末〜12月末の期間限定。",
    tip: "ヴァン・ショー（ホットワイン）を片手に散策。大聖堂前が最大の会場。" },

  // ===== Mont-Saint-Michel (8) =====
  { id: "msm-abbey", name: "モン・サン・ミシェル修道院", region: "mont-saint-michel",
    categories: ["history","culture"], timeSlot: "morning", hours: 2.5,
    lat: 48.6361, lng: -1.5115,
    description: "「西洋の驚異」と称される修道院。ゴシックとロマネスクの建築が融合。",
    tip: "朝一番の訪問が最も空いている。オーディオガイドで歴史を学ぼう。" },
  { id: "msm-bay", name: "湾の干潟ウォーク", region: "mont-saint-michel",
    categories: ["nature"], timeSlot: "morning", hours: 3,
    lat: 48.6350, lng: -1.5050,
    description: "干潮時に現れる広大な干潟を歩く。ガイド付きツアーで安全に楽しめる。",
    tip: "必ず認定ガイド付きで参加を。潮の流れは非常に危険。長靴推奨。" },
  { id: "msm-ramparts", name: "城壁散策", region: "mont-saint-michel",
    categories: ["history","nature"], timeSlot: "afternoon", hours: 1.5,
    lat: 48.6355, lng: -1.5110,
    description: "島を取り囲む中世の城壁を歩く。湾を一望する絶景ポイントが点在。",
    tip: "夕暮れ時の眺めが特に美しい。" },
  { id: "msm-omelette", name: "名物オムレツ体験", region: "mont-saint-michel",
    categories: ["food"], timeSlot: "afternoon", hours: 1.5,
    lat: 48.6358, lng: -1.5108,
    description: "ラ・メール・プーラールの巨大ふわふわオムレツ。伝統の味を体験。",
    tip: "観光地価格だが一度は試す価値あり。テイクアウトでクッキーも人気。" },
  { id: "msm-nightview", name: "夜景鑑賞", region: "mont-saint-michel",
    categories: ["nature","culture"], timeSlot: "evening", hours: 1.5,
    lat: 48.6320, lng: -1.5130,
    description: "ライトアップされたモン・サン・ミシェルは幻想的な美しさ。",
    tip: "対岸のダムからの眺めがベストスポット。宿泊者限定の体験。" },
  { id: "msm-museum", name: "歴史博物館", region: "mont-saint-michel",
    categories: ["history"], timeSlot: "afternoon", hours: 1,
    lat: 48.6356, lng: -1.5105,
    description: "モン・サン・ミシェルの歴史と建設過程を学べる小さな博物館。",
    tip: "修道院とセットで訪れると理解が深まる。" },
  { id: "msm-grandrue", name: "グランド・リュ散策", region: "mont-saint-michel",
    categories: ["shopping","food"], timeSlot: "morning", hours: 1.5,
    lat: 48.6354, lng: -1.5100,
    description: "島のメインストリート。土産物店やクレープリーが並ぶ。",
    tip: "混雑を避けるなら朝8時台がおすすめ。ガレットやシードルを楽しんで。" },
  { id: "msm-polders", name: "ポルダー地帯散歩", region: "mont-saint-michel",
    categories: ["nature"], timeSlot: "evening", hours: 1.5,
    lat: 48.6250, lng: -1.5200,
    description: "干拓地に広がるのどかな農地。羊の放牧風景とモン・サン・ミシェルの遠景。",
    tip: "プレ・サレ（塩草地の羊肉）は地元の名産品。" },

  // ===== Loire (8) =====
  { id: "loire-chambord", name: "シャンボール城", region: "loire",
    categories: ["history","culture"], timeSlot: "morning", hours: 3,
    lat: 47.6161, lng: 1.5170,
    description: "ロワール最大の城。ダ・ヴィンチ設計の二重らせん階段が見どころ。",
    tip: "広大な敷地なので半日は確保。レンタサイクルで庭園を巡るのもおすすめ。" },
  { id: "loire-chenonceau", name: "シュノンソー城", region: "loire",
    categories: ["history","culture","nature"], timeSlot: "morning", hours: 2.5,
    lat: 47.3249, lng: 1.0704,
    description: "シェール川にかかる優美な城。「貴婦人たちの城」と呼ばれる。",
    tip: "花の庭園が美しい春〜夏がベストシーズン。" },
  { id: "loire-amboise", name: "アンボワーズ城とクロ・リュセ", region: "loire",
    categories: ["history","culture"], timeSlot: "afternoon", hours: 2.5,
    lat: 47.4133, lng: 0.9863,
    description: "レオナルド・ダ・ヴィンチが晩年を過ごしたクロ・リュセ城も隣接。",
    tip: "ダ・ヴィンチの発明品の復元模型は子どもから大人まで楽しめる。" },
  { id: "loire-wine", name: "ロワールワインテイスティング", region: "loire",
    categories: ["food"], timeSlot: "afternoon", hours: 2.5,
    lat: 47.3614, lng: 0.6848,
    description: "ソーヴィニヨン・ブランやシノンなど、多彩なロワールワインを試飲。",
    tip: "ヴーヴレやソミュールのカーヴ（洞窟醸造所）がユニーク。" },
  { id: "loire-villandry", name: "ヴィランドリー城の庭園", region: "loire",
    categories: ["nature","history"], timeSlot: "morning", hours: 2,
    lat: 47.3400, lng: 0.5140,
    description: "フランス式庭園の最高峰。幾何学模様の装飾庭園と菜園が見事。",
    tip: "6〜7月のバラの季節が特に美しい。" },
  { id: "loire-troglodyte", name: "トログロディット洞窟住居", region: "loire",
    categories: ["history","culture"], timeSlot: "afternoon", hours: 2,
    lat: 47.2500, lng: -0.0710,
    description: "岩壁を掘って作られた伝統的な洞窟住居。今もワイン貯蔵庫として現役。",
    tip: "ソミュール周辺に多い。キノコ栽培の見学もできる。" },
  { id: "loire-cycling", name: "ロワール川サイクリング", region: "loire",
    categories: ["nature"], timeSlot: "morning", hours: 3,
    lat: 47.3941, lng: 0.6849,
    description: "「ロワール・ア・ヴェロ」の整備されたサイクリングロードを走る。",
    tip: "電動アシスト自転車のレンタルもあり。城から城へのルートが人気。" },
  { id: "loire-touraine", name: "トゥレーヌ地方の美食", region: "loire",
    categories: ["food"], timeSlot: "evening", hours: 2,
    lat: 47.3941, lng: 0.6848,
    description: "リエット、ヤギチーズ（サント・モール）、タルトタタンなど地方の味覚。",
    tip: "地元のマルシェで食材を購入してピクニックも楽しい。" },

  // ===== Provence (8) =====
  { id: "provence-lavender", name: "ラベンダー畑", region: "provence",
    categories: ["nature"], timeSlot: "morning", hours: 3,
    lat: 43.8900, lng: 5.8900,
    description: "6月下旬〜8月上旬に紫色の絨毯が広がるプロヴァンスの象徴的風景。",
    tip: "ヴァランソル高原が最も有名。セナンク修道院前のラベンダーも人気。" },
  { id: "provence-avignon", name: "アヴィニョン教皇庁宮殿", region: "provence",
    categories: ["history","culture"], timeSlot: "morning", hours: 2.5,
    lat: 43.9508, lng: 4.8075,
    description: "中世に教皇庁が置かれた巨大なゴシック宮殿。世界遺産。",
    tip: "7月の演劇祭期間は特に賑やか。サン・ベネゼ橋もセットで。" },
  { id: "provence-aixenp", name: "エクス・アン・プロヴァンス", region: "provence",
    categories: ["culture","food","shopping"], timeSlot: "afternoon", hours: 3,
    lat: 43.5297, lng: 5.4474,
    description: "セザンヌの街。プラタナス並木のミラボー通りでカフェ文化を堪能。",
    tip: "カリソン（アーモンド菓子）がお土産に最適。土曜のマルシェが充実。" },
  { id: "provence-gordes", name: "ゴルド村", region: "provence",
    categories: ["nature","history"], timeSlot: "morning", hours: 2,
    lat: 43.9116, lng: 5.2003,
    description: "断崖に張り付くように立つ「フランスの最も美しい村」の一つ。",
    tip: "車でのアクセスが便利。近くのセナンク修道院も合わせて訪問。" },
  { id: "provence-market", name: "プロヴァンスのマルシェ巡り", region: "provence",
    categories: ["food","shopping"], timeSlot: "morning", hours: 2.5,
    lat: 43.9200, lng: 5.1480,
    description: "オリーブ、ハーブ、チーズ、蜂蜜など南仏の産物が並ぶ色鮮やかな市場。",
    tip: "曜日ごとに各町で開催。リル・シュル・ラ・ソルグの日曜市が有名。" },
  { id: "provence-roussillon", name: "ルシヨン村（オークルの村）", region: "provence",
    categories: ["nature","culture"], timeSlot: "afternoon", hours: 2,
    lat: 43.9019, lng: 5.2935,
    description: "赤や黄色のオークル（黄土）に彩られた独特の景観を持つ村。",
    tip: "オークルの小道（Sentier des Ocres）の散策路がおすすめ。服の汚れに注意。" },
  { id: "provence-rosewine", name: "プロヴァンスロゼワイン体験", region: "provence",
    categories: ["food"], timeSlot: "evening", hours: 2,
    lat: 43.3600, lng: 5.7500,
    description: "世界のロゼワインの約半分を生産するプロヴァンスで本場の味を。",
    tip: "バンドールやコート・ド・プロヴァンスのドメーヌ訪問がおすすめ。" },
  { id: "provence-verdon", name: "ヴェルドン渓谷", region: "provence",
    categories: ["nature"], timeSlot: "morning", hours: 4,
    lat: 43.7560, lng: 6.3270,
    description: "ヨーロッパのグランドキャニオン。エメラルドグリーンの水と断崖絶壁。",
    tip: "カヤックやペダルボートで渓谷を楽しめる。車でのアクセスが必要。" },

  // ===== Normandy (10) =====
  { id: "normandy-dday", name: "ノルマンディー上陸作戦ビーチ", region: "normandy",
    categories: ["history"], timeSlot: "morning", hours: 4,
    lat: 49.3625, lng: -0.8732,
    description: "オマハビーチやユタビーチなど、第二次世界大戦の歴史的な海岸。",
    tip: "ガイドツアー参加が歴史を深く理解するのにおすすめ。" },
  { id: "normandy-bayeux", name: "バイユーのタペストリー", region: "normandy",
    categories: ["history","culture"], timeSlot: "morning", hours: 2,
    lat: 49.2764, lng: -0.7030,
    description: "1066年のノルマン征服を描いた全長70mの中世刺繍。ユネスコ記憶遺産。",
    tip: "オーディオガイドでストーリーを追うと感動的。" },
  { id: "normandy-honfleur", name: "オンフルール", region: "normandy",
    categories: ["culture","nature"], timeSlot: "afternoon", hours: 2.5,
    lat: 49.4185, lng: 0.2331,
    description: "印象派画家たちが愛した美しい港町。旧港の風景は絵画のよう。",
    tip: "エリック・サティの生家博物館もあり。シーフードレストランも充実。" },
  { id: "normandy-etretat", name: "エトルタの断崖", region: "normandy",
    categories: ["nature"], timeSlot: "morning", hours: 3,
    lat: 49.7073, lng: 0.2048,
    description: "モネが描いた白亜の断崖とアーチ。ノルマンディーを代表する絶景。",
    tip: "崖の上のハイキングコースからの眺めが素晴らしい。風が強いので注意。" },
  { id: "normandy-rouen", name: "ルーアン大聖堂", region: "normandy",
    categories: ["history","culture"], timeSlot: "afternoon", hours: 1.5,
    lat: 49.4401, lng: 1.0941,
    description: "モネが連作を描いたゴシック大聖堂。ジャンヌ・ダルクの街としても有名。",
    tip: "旧市街の木組みの家々も見どころ。大時計通りは必見。" },
  { id: "normandy-camembert", name: "カマンベールチーズ体験", region: "normandy",
    categories: ["food"], timeSlot: "afternoon", hours: 2,
    lat: 48.8800, lng: 0.1730,
    description: "カマンベールの本場でチーズ工房を見学。試食付きツアーが人気。",
    tip: "ヴィムティエの町のカマンベール博物館も面白い。" },
  { id: "normandy-giverny", name: "ジヴェルニー（モネの庭園）", region: "normandy",
    categories: ["nature","culture"], timeSlot: "morning", hours: 2.5,
    lat: 49.0758, lng: 1.5335,
    description: "モネが「睡蓮」を描いた庭園と日本橋。印象派ファン必見の聖地。",
    tip: "4〜10月のみ開館。朝一番が空いている。パリから日帰り可能。" },
  { id: "normandy-cidre", name: "シードル街道めぐり", region: "normandy",
    categories: ["food","nature"], timeSlot: "afternoon", hours: 3,
    lat: 49.0500, lng: 0.0600,
    description: "りんごの産地を巡り、シードルやカルヴァドスの醸造所を訪問。",
    tip: "ペイ・ドージュ地方がシードルの名産地。試飲は運転に注意。" },
  { id: "normandy-deauville", name: "ドーヴィル", region: "normandy",
    categories: ["nature","shopping"], timeSlot: "afternoon", hours: 2,
    lat: 49.3583, lng: 0.0750,
    description: "優雅なビーチリゾート。映画祭でも知られるノルマンディーの宝石。",
    tip: "有名人の名前が書かれた板張りの遊歩道を散策。" },
  { id: "normandy-seafood", name: "ノルマンディー・シーフード", region: "normandy",
    categories: ["food"], timeSlot: "evening", hours: 2,
    lat: 49.4190, lng: 0.2340,
    description: "新鮮な牡蠣、ムール貝、オマール海老など大西洋の恵みを堪能。",
    tip: "オンフルールやカンカルで新鮮な牡蠣を。白ワインと一緒に。" }
];

const REGIONS = {
  paris: "パリ",
  lyon: "リヨン",
  marseille: "マルセイユ",
  nice: "ニース",
  bordeaux: "ボルドー",
  strasbourg: "ストラスブール",
  "mont-saint-michel": "モン・サン・ミシェル",
  loire: "ロワール渓谷",
  provence: "プロヴァンス",
  normandy: "ノルマンディー"
};

const CATEGORIES = {
  culture: "文化・芸術",
  food: "グルメ",
  nature: "自然・景色",
  shopping: "ショッピング",
  history: "歴史"
};
